### ISSUE TITLE
Hi, is this app still being updated?

### ISSUE THREAD

**Issue by bajopants** [dbkynd/controlcast#36]
Hi! 

Is this app still being updated?

I would love the toggle option mentioned here https://github.com/dbkynd/controlcast/issues/28 and would happily commission the feature!

**Comment by dbkynd** [comment]
Unfortunately, not really.
I myself only had a launchpad mini which I wrote this application for. I see a lot or request for supporting other devices, but without having those devices myself for testing is a bit difficult.
My own launchpad mini suffered damage in a long drop during a recent move so I'd have to get a new one to continue. Which is not out of the question, it just helps explains the lack of support recently.
And lastly, the app was primarily written for use by AnneMunition, who I mod for, and who has since switched to using an Elgato StreamDeck. So a lot of my motivation for keeping ControlCast up to date has been lost.
